# https://codeclimate.com/
#
engines:
    duplication:
        enabled: true
        config:
            languages:
                - python
    pep8:
        enabled: true
    radon:
        enabled: true
        config: 
            threshold: "D"
    fixme:
        enabled: true

ratings:
    paths:
        - "src/rstxml2db/**"

exclude_paths:
    - tests/**
    - test/**
    - doc/**
    - dist/**
    - build/**
    - "*.cfg"
    - "*.in"
    - "LICENSE"
    - "*.txt"
    - "*.rst"
