# config file for automatic testing at travis-ci.org
language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"

env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

# command to install dependencies
install:
    - pip install .
    - pip install -r travis_requirements.txt

# command to run tests
script:
    - py.test -s -vv
    # -s -v --cov-report term-missing --cov=rstxml2db

# after_success:
#    codecov

