# config file for automatic testing at travis-ci.org
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6-dev"

env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so


# command to install dependencies
install:
    - pip install -U pip setuptools
    - pip install .
    - pip install -r travis_requirements.txt

# command to run tests
script:
    - py.test -l -vv --no-cov-on-fail --cov=rstxml2db --cov-report=term-missing
    #- coverage run $VIRTUAL_ENV/bin/py.test -l -v
    - travis-sphinx --nowarn --source=doc build

after_success:
    - codecov
    - travis-sphinx deploy
